name: Build Windows Executable

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Executable via PyInstaller
        uses: Martin005/pyinstaller-action@v1.2.0
        with:
          python_ver: '3.11'
          spec: 'app.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'NTK_Downloader_Windows'
          options: --onefile, --windowed, --name "NTK_Downloader", --collect-all curl_cffi
